steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/diccionario-misak', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/diccionario-misak']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'diccionario-misak',
        '--image', 'gcr.io/$PROJECT_ID/diccionario-misak',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars', 'MONGODB_URI=mongodb+srv://misakuser:misak123@cluster0.otgo1hr.mongodb.net/diccionario?retryWrites=true&w=majority',
      ]
