steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/misak-dictionary:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/misak-dictionary:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'misak-dictionary',
           '--image', 'gcr.io/$PROJECT_ID/misak-dictionary:$COMMIT_SHA',
           '--region', 'us-central1',
           '--platform', 'managed',
           '--allow-unauthenticated',
           '--set-env-vars', 'NODE_ENV=production',
           '--set-env-vars', 'MONGODB_URI=$_MONGODB_URI',
           '--port', '8080']
    secretEnv: ['_MONGODB_URI']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/MONGODB_URI/versions/latest
    env: '_MONGODB_URI'

options:
  logging: CLOUD_LOGGING_ONLY