steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/misak-dictionary:$COMMIT_SHA', '.']
    timeout: 600s
    id: 'build'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/misak-dictionary:$COMMIT_SHA']
    timeout: 600s
    id: 'push'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy misak-dictionary \
          --image gcr.io/$PROJECT_ID/misak-dictionary:$COMMIT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --set-secrets MONGODB_URI=MONGODB_URI:latest \
          --set-env-vars NODE_ENV=production
    timeout: 1200s
    id: 'deploy'


options:
  logging: CLOUD_LOGGING_ONLY
  # Sin machineType específico (usa el default)
  # O usa uno más pequeño si es necesario:
  # machineType: 'E2_HIGHCPU_2'