steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '-t', 'gcr.io/$PROJECT_ID/misak-dictionary:$COMMIT_SHA',
           '--build-arg', 'NODE_ENV=production',
           '.']
    timeout: 600s

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/misak-dictionary:$COMMIT_SHA']
    timeout: 600s

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'misak-dictionary',
           '--image', 'gcr.io/$PROJECT_ID/misak-dictionary:$COMMIT_SHA',
           '--region', 'us-central1',
           '--platform', 'managed',
           '--allow-unauthenticated',
           '--port', '8080',
           '--timeout', '600s',
           '--cpu', '1',
           '--memory', '512Mi',
           '--min-instances', '1',
           '--set-env-vars', 'NODE_ENV=production',
           '--set-env-vars', 'MONGODB_URI=$_MONGODB_URI']
    secretEnv: ['_MONGODB_URI']
    timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/MONGODB_URI/versions/latest
    env: '_MONGODB_URI'